name: 'Verify Running Pods'
description: 'Check if pods for release are running'
inputs:
  release-name:
    description: 'Name of the Helm release'
    required: true
  namespace:
    description: 'Kubernetes namespace'
    required: true

outputs:
  pods_running:
    description: 'The k8s pods are running'
    value: ${{ steps.check-pods.outputs.pods_running }}


runs:
  using: 'composite'
  steps:
    - name: Check pod status
      id: check-pods
      shell: bash
      run: |
        POD_STATUS=$(kubectl get pods -n ${{ inputs.namespace }} -l app.kubernetes.io/instance=${{ inputs.release-name }} -o jsonpath='{.items[*].status.phase}')
        READY_PODS=$(kubectl get pods -n ${{ inputs.namespace }} -l app.kubernetes.io/instance=${{ inputs.release-name }} --field-selector=status.phase=Running --no-headers | wc -l)
        
        echo "Pod statuses: $POD_STATUS"
        echo "Ready pods: $READY_PODS"
        
        if [[ "$POD_STATUS" == *"Running"* && $READY_PODS -gt 0 ]]; then
          echo "✅ At least one pod is running"
          echo "pods_running=true" >> $GITHUB_OUTPUT
        else
          echo "::error::❌ No pods in Running state"
          echo "pods_running=false" >> $GITHUB_OUTPUT
          exit 1
        fi