name: "Build and push docker image"
inputs:
  cache-key:
    description: 'Cache key for restoring dependencies'
    required: true
    type: string
  app-version:
    description: 'Application version'
    required: true
    type: string
  build-number:
    description: 'Build number'
    required: true
    type: string
  registry:
    description: 'Docker registry URL'
    required: true
    type: string
  repository:
    description: 'Docker repository name'
    required: true
    type: string
  cookie-secret:
    description: 'Cookie secret for the application'
    required: true
    type: string
  debug:
    description: 'Enable debug mode'
    required: false
    type: boolean
    default: false
runs:
  using: "composite"

  steps:
    - name: Restore dependencies from cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container  # Use the Docker container driver for better performance

    - name: Define image tag with UI
      id: define-image-tag
      run: |
        set -e  # Fail the script on any error
        GIT_REF=$(git rev-parse --short HEAD)
        IMAGE_TAG="gpfd-ui-${{ inputs.app-version }}-$GIT_REF"
        echo "Defined image tag: $IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      shell: bash

    - name: Create .env file
      shell: bash
      run: |
        set -e  # Fail the script on any error
        
        # Validate required inputs and secrets
        # if [ -z "${{ inputs.cookie-secret }}" ]; then
        #  echo "Error: COOKIE_SECRET is not set."
        #  exit 1
        # fi
        
        # Create the .env file using a heredoc block for better readability
        cat <<EOF > .env
        # Cookie secret - unique, long string to encrypt the cookies
        COOKIE_SECRET=fooBar

        # Set rate limiting - how many requests can be made by an IP over a time period
        RATE_LIMIT_MAX=100
        RATE_WINDOW_MS=900000  # 15 * 60 * 1000 = 900000
        
        # Service details
        SERVICE_NAME='Get Legal Aid Data'
        SERVICE_PHASE='Alpha'
        
        # API details
        API_PROTOCOL='http'
        API_HOST='localhost:8080'
        EOF
        
        echo ".env file created successfully."

    - name: Build and push Docker image to container repository
      run: |
        set -e  # Fail the script on any error
        export DOCKER_BUILDKIT=1
        
        echo "Building Docker image with tag: ${{ inputs.registry }}/${{ inputs.repository }}:${{ env.IMAGE_TAG }}"
        docker buildx build . \
          --build-arg BUILD_NUMBER=${{ inputs.build-number }} \
          --build-arg APP_VERSION=${{ inputs.app-version }} \
          --build-arg GIT_REF=$(git rev-parse --short HEAD) \
          -t ${{ inputs.registry }}/${{ inputs.repository }}:${{ env.IMAGE_TAG }} \
          --push \
          --progress=plain \
          --compress 
        echo "Successfully pushed Docker image to ${{ inputs.registry }}/${{ inputs.repository }}:${{ env.IMAGE_TAG }}"
      shell: bash
      env:
        IMAGE_TAG: ${{ env.IMAGE_TAG }}

    - name: Verify Docker image
      if: ${{ inputs.debug }}
      run: |
        set -e  # Fail the script on any error
        echo "Pulling Docker image: ${{ inputs.registry }}/${{ inputs.repository }}:${{ env.IMAGE_TAG }}"
        docker pull ${{ inputs.registry }}/${{ inputs.repository }}:${{ env.IMAGE_TAG }}
        echo "Inspecting Docker image:"
        docker run --rm ${{ inputs.registry }}/${{ inputs.repository }}:${{ env.IMAGE_TAG }} ls -la /app
      shell: bash

    - name: Add build summary
      run: |
        echo "### Docker Image Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image Tag:** ${{ inputs.registry }}/${{ inputs.repository }}:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Number:** ${{ inputs.build-number }}" >> $GITHUB_STEP_SUMMARY
        echo "- **App Version:** ${{ inputs.app-version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Git Ref:** $(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry:** ${{ inputs.registry }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository:** ${{ inputs.repository }}" >> $GITHUB_STEP_SUMMARY
      shell: bash