name: "Build and push docker image"
runs:
  using: "composite"

  steps:
    - name: Restore dependencies from cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container  # Use the Docker container driver for better performance

    - name: Define image tag with UI
      id: define-image-tag
      run: |
        set -e  # Fail the script on any error
        GIT_REF=$(git rev-parse --short HEAD)
        IMAGE_TAG="ui-${{ inputs.app-version }}-$GIT_REF"
        echo "Defined image tag: $IMAGE_TAG"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      shell: bash

    - name: Build and push Docker image to container repository
      run: |
        set -e  # Fail the script on any error
        echo "Building Docker image with tag: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}"
        docker buildx build . \
          --build-arg BUILD_NUMBER=${{ inputs.build-number }} \
          --build-arg APP_VERSION=${{ inputs.app-version }} \
          --build-arg GIT_REF=$(git rev-parse --short HEAD) \
          -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} \
          --push
        echo "Successfully pushed Docker image to ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}"
      env:
        REGISTRY: ${{ env.REGISTRY }}
        REPOSITORY: ${{ env.REPOSITORY }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      shell: bash

    - name: Add build summary
      run: |
        echo "### Docker Image Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image Tag:** ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Number:** ${{ inputs.build-number }}" >> $GITHUB_STEP_SUMMARY
        echo "- **App Version:** ${{ inputs.app-version }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Git Ref:** $(git rev-parse --short HEAD)" >> $GITHUB_STEP_SUMMARY
        echo "- **Registry:** ${{ env.REGISTRY }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository:** ${{ env.REPOSITORY }}" >> $GITHUB_STEP_SUMMARY
      shell: bash