name: "Build and push docker image"
runs:
  using: "composite"

  steps:
    - name: Restore dependencies from cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Define image tag with UI
      id: define-image-tag
      run: |
        GIT_REF=$(git rev-parse --short HEAD)
        IMAGE_TAG="ui-${{ inputs.app-version }}-$GIT_REF"
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
      shell: bash

    - name: Build and push Docker image to container repository
      run: |
        docker build \
          --build-arg BUILD_NUMBER=${{ inputs.build-number }} \
          --build-arg APP_VERSION=${{ inputs.app-version }} \
          --build-arg GIT_REF=$(git rev-parse --short HEAD) \
          -t ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }} .
        docker push ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
      env:
        REGISTRY: ${{ env.REGISTRY }}
        REPOSITORY: ${{ env.REPOSITORY }}
        IMAGE_TAG: ${{ env.IMAGE_TAG }}
      shell: bash