{ { - if .Values.ingress.enabled - } }
  { { - $fullName := include "payforlegalaid-ui.fullname" . - } }
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { { include "payforlegalaid-ui.fullname" . } }
  labels:
    { { - include "payforlegalaid-ui.labels" . | nindent 4 } }
  annotations:
    { { - if .Values.ingress.annotations } }
      { { - toYaml .Values.ingress.annotations | nindent 4 } }
      { { - end } }
      external-dns.alpha.kubernetes.io/aws-weight: "{{ .Values.ingress.awsWeight | default "100" }}"
      external-dns.alpha.kubernetes.io/set-identifier: "{{ $fullName }}-{{ .Release.Namespace }}-{{- .Values.ingress.cluster.name -}}"
spec:
  { { - if .Values.ingress.rules } }
  rules:
    { { - toYaml .Values.ingress.rules | nindent 4 } }
  { { - else } }
  defaultBackend:
    service:
      name: { { include "payforlegalaid-ui.fullname" . } }
      port:
        number: { { .Values.service.port } }
  { { - end } }
  { { - if .Values.ingress.tls } }
  tls:
    { { - toYaml .Values.ingress.tls | nindent 4 } }
  { { - end } }
  { { - end } }