{{- if .Values.ingress.enabled -}}
{{- $fullname := include "payforlegalaid-ui.fullname" . -}}
{{- $servicePort := required "service.port is required" .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullname }}
  labels:
    {{- include "payforlegalaid-ui.labels" . | nindent 4 }}
    app.kubernetes.io/component: ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: "payforlegalaid-ui-{{ .Release.Namespace }}-{{ .Values.ingress.clusterColor }}"
    external-dns.alpha.kubernetes.io/aws-weight: "{{ .Values.ingress.awsWeight | default "100" }}"
    nginx.ingress.kubernetes.io/backend-protocol: "{{ .Values.ingress.backendProtocol | default "http" }}"
    nginx.ingress.kubernetes.io/affinity: "{{ .Values.ingress.affinity | default "cookie" }}"
    nginx.ingress.kubernetes.io/affinity-mode: "persistent"
    nginx.ingress.kubernetes.io/session-cookie-name: "INGRESSCOOKIE"
    nginx.ingress.kubernetes.io/session-cookie-secure: "true"
    nginx.ingress.kubernetes.io/session-cookie-samesite: "Lax"
    nginx.ingress.kubernetes.io/limit-rpm: "{{ .Values.ingress.rateLimit | default 1000 }}"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: "{{ $fullname }}.{{ .Release.Namespace }}.svc.cluster.local"

    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName | default "default" }}
  {{- if .Values.ingress.rules }}
  rules:
    {{- toYaml .Values.ingress.rules | nindent 4 }}
  {{- else }}
  defaultBackend:
    service:
      name: {{ $fullname }}
      port:
        number: {{ $servicePort }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
  {{- end }}