name: "Verify Docker Image"
description: "Verify the Docker image by pulling and inspecting it."
inputs:
  registry:
    description: "Docker registry URL"
    required: true
    type: string
  repository:
    description: "Docker repository name"
    required: true
    type: string
  image-tag:
    description: "Docker image tag"
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Validate inputs
      shell: bash
      run: |
        if [[ -z "${{ inputs.registry }}" || -z "${{ inputs.repository }}" || -z "${{ inputs.image-tag }}" ]]; then
          echo "::error::Missing required inputs (registry, repository, or tag)"
          exit 1
        fi

    - name: Pull and inspect image
      shell: bash
      run: |
        set -e  # Fail the script on any error
        echo "Pulling Docker image: ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}"
        docker pull ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }}
        echo "Inspecting Docker image:"
        docker run --rm ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.image-tag }} ls -la /app
