name: Lint and Format
description: Run Prettier and ESLint
runs:
  using: "composite"
  steps:
    - name: Restore dependencies from cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ inputs.cache-key }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Run Prettier
      run: npm run format:check
      shell: bash

    - name: Install ESLint8
      run: |
        npm install eslint@8.x --save-dev
        npm install eslint-plugin-jsdoc --save-dev
      shell: bash

    - name: Run ESLint8
      run: npx eslint . --ignore-pattern "**/node_modules/*" --fix
      shell: bash
