name: "Create/Update and Deploy Helm Chart"
runs:
  using: "composite"

  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create or update Helm chart
      id: create-update-helm-chart
      run: |
        set -e  # Fail the script on any error

        CHART_DIR="./helm_deploy/payforlegalaid-ui"
        VALUES_FILE="$CHART_DIR/values.yaml"

        if [ ! -d "$CHART_DIR" ]; then
          echo "Creating new Helm chart in $CHART_DIR..."
          helm create $CHART_DIR
        else
          echo "Helm chart already exists in $CHART_DIR."
        fi

        echo "Updating values.yaml with new image tag: ${{ env.IMAGE_TAG }}"
        yq eval ".image.tag = \"${{ env.IMAGE_TAG }}\"" -i $VALUES_FILE

        echo "Updated values.yaml:"
        cat $VALUES_FILE
      shell: bash

    - name: Deploy Helm chart
      id: deploy-helm-chart
      env:
        KUBE_NAMESPACE: ${{ env.KUBE_NAMESPACE_DEV }}
        KUBE_CLUSTER: ${{ env.KUBE_CLUSTER_DEV }}
        REGISTRY: ${{ env.registry }}
        REPOSITORY: ${{ env.DEV_ECR_REPOSITORY }}
        NAMESPACE: ${{ env.KUBE_NAMESPACE_DEV }}
        KUBE_TOKEN_DEV: ${{ env.KUBE_TOKEN_DEV }}
        ENV_NAME: dev
      run: |
        set -e  # Fail the script on any error
        
        kubectl config set-cluster ${KUBE_CLUSTER} --certificate-authority=./ca.crt --server=https://${KUBE_CLUSTER}
        kubectl config set-credentials deploy-user --token=${{ KUBE_TOKEN_DEV }}
        kubectl config set-context ${KUBE_CLUSTER} --cluster=${KUBE_CLUSTER} --user=deploy-user --namespace=${KUBE_NAMESPACE}
        kubectl config use-context ${KUBE_CLUSTER}

        CHART_DIR="./charts/payforlegalaid-ui"
        RELEASE_NAME="payforlegalaid-ui"
        NAMESPACE="laa-get-payments-finance-data-dev"

        echo "Deploying Helm chart..."
        helm upgrade --install payforlegalaid-ui ./payforlegalaid-ui \
          --namespace laa-get-payments-finance-data-dev \
          --set image.tag=${{ env.IMAGE_TAG }} \
          --atomic
        echo "Helm chart deployed successfully!"
      shell: bash
