name: Deploy Helm Chart

on:
  workflow_call:
    inputs:
      debug:
        description: 'Enable debugging'
        required: false
        type: boolean
        default: false
      chart-dir:
        description: "The directory where the Helm chart is located"
        required: true
        type: string
      image-tag:
        description: "The image tag to update in values.yaml"
        required: true
        type: string

jobs:
  deploy-helm-chart:
    runs-on: ubuntu-latest
    environment: development
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check if Helm chart exists
        uses: './.github/actions/helm/check'
        with:
          chart-dir: ${{ inputs.chart-dir }}

      - name: Validate values.yaml
        uses: './.github/actions/helm/validate'
        with:
          chart-dir: ${{ inputs.chart-dir }}

      - name: Create or update Helm chart
        uses: './.github/actions/helm/update'
        with:
          chart-dir: ${{ inputs.chart-dir }}
          image-tag: ${{ github.sha }}

      - name: Add build summary
        uses: './.github/actions/helm/summary'
        with:
          chart-dir: ${{ inputs.chart-dir }}
          image-tag: ${{ github.sha }}

      - name: Debug Helm Chart Output
        if: ${{ inputs.debug }}
        run: |
          echo "Helm Chart Version: ${{ github.sha }}