name: Image Creation Workflow

on:
  workflow_call:
    inputs:
      build-number:
        description: 'Build number for the Docker image'
        required: false
        type: string
      app-version:
        description: 'Application version for the Docker image'
        required: false
        type: string
        default: '1.0.0'
      chart-dir:
        description: 'Path to the Helm chart directory'
        required: false
        type: string
        default: './helm_deploy/payforlegalaid-ui'
      debug:
        description: 'Enable debugging'
        required: false
        type: boolean
        default: false
      environment:
        description: 'Target environment (DEV, UAT, PROD)'
        required: true
        type: string
        default: 'DEV'
      app-host:
        description: "The hostname for the Kubernetes Ingress (e.g., 'app.example.com')"
        required: true
        type: string
    outputs:
      registry:
        description: 'ECR Registry URL'
        value: ${{ jobs.build-docker.outputs.registry }}
      image-tag:
        description: 'Docker image tag'
        value: ${{ jobs.build-docker.outputs.image-tag }}
      helm_manifest:
        description: "Base64-encoded custom values.yaml for Helm (overrides defaults)"
        value: ${{ jobs.build-helm-chart.outputs.helm_manifest }}

jobs:
  build-docker:
    uses: ./.github/workflows/build-docker-workflow.yml
    with:
      app-version: ${{ inputs.app-version }}
      environment: ${{ inputs.environment }}
      build-number: ${{ inputs.build-number }}
      debug: ${{ inputs.debug }}
    secrets: inherit

  build-helm-chart:
    needs: build-docker
    uses: ./.github/workflows/build-helm-workflow.yml
    with:
      chart-dir: ${{ inputs.chart-dir }}
      image-tag: ${{ needs.build-docker.outputs.image-tag }}
      debug: ${{ inputs.debug }}
      environment: ${{ inputs.environment }}
      app-host: ${{ inputs.app-host }}