name: Test AWS Credentials

on: [push]

jobs:
  test-aws-credentials:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ env.ECR_REGION }}

      - name: Verify AWS Credentials
        run: |
          aws sts get-caller-identity