name: Calling Workflow

on: [push]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          cookie-secret: "foo-bar"

  useCallable:
    needs: setup
    uses: './.github/workflows/callable_workflow.yml'
    with:
      name: 'Jimin'