name: Callable Workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Name for greeting'
        required: true
        type: 'string'

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - id: greeting
        run: echo "::set-output name=message::Hello, ${{ inputs.name }}"