name: Extracts application version from package.json

on:
  workflow_call:
    outputs:
      app-version:
        description: "The version extracted from package.json"
        value: ${{ jobs.metadata-extractor.outputs.app-version }}

jobs:
  metadata-extractor:
    runs-on: ubuntu-latest
    outputs:
      app-version: ${{ steps.read-package-json.outputs.app-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          sparse-checkout: package.json
          sparse-checkout-cone-mode: false

      - name: Install jq
        shell: bash
        run: |
          if ! command -v jq &> /dev/null; then
            if command -v brew &> /dev/null; then
              brew install jq
            elif command -v apt-get &> /dev/null; then
              sudo apt-get update -qq && sudo apt-get install -y jq
            else
              JQ_VERSION=1.7
              curl -sSL -o /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-$JQ_VERSION/jq-linux64
              chmod +x /usr/local/bin/jq
            fi
          fi

      - name: Validate package.json exists
        id: file-check
        shell: bash
        run: |
          if [ ! -f "package.json" ]; then
            echo "::error::package.json not found in repository root"
            exit 1
          fi

      - name: Extract app version from package.json
        id: read-package-json
        run: |
          APP_VERSION=$(jq -r .version package.json)
          if [ -z "$APP_VERSION" ]; then
            echo "Error: Failed to extract app version from package.json"
            exit 1
          fi
          echo "Extracted app version: $APP_VERSION"
          echo "app-version=$APP_VERSION" >> $GITHUB_OUTPUT