name: Feature Branch CI

on:
  workflow_call:
    inputs:
      name:
        description: 'Name for greeting'
        required: true
        type: 'string'

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-deps.outputs.cache-key }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        id: setup
        uses: ./.github/actions/setup
        with:
          cookie-secret: "foo-bar"
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        id: build
        uses: ./.github/actions/build
        with:
          cache-key: ${{ needs.setup.outputs.cache-key }}

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test
        uses: ./.github/actions/test

  format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Format
        uses: ./.github/actions/format

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Lint
        uses: ./.github/actions/lint
