name: Image Creation Workflow

on:
  workflow_call:
    inputs:
      build-number:
        description: 'Build number for the Docker image'
        required: false
        type: number
        default: 1
      app-version:
        description: 'Application version for the Docker image'
        required: false
        type: string
        default: '1.0.0'
      chart-dir:
        description: 'Path to the Helm chart directory'
        required: false
        type: string
        default: './helm_deploy/payforlegalaid-ui'
      debug:
        description: 'Enable debugging'
        required: false
        type: boolean
        default: false
      environment:
        description: 'Target environment (DEV, UAT, PROD)'
        required: true
        type: string
        default: 'DEV'
    outputs:
      registry:
        description: 'ECR Registry URL'
        value: ${{ jobs.authenticate-and-prepare.outputs.registry }}
      image-tag:
        description: 'Docker image tag'
        value: ${{ jobs.authenticate-and-prepare.outputs.image-tag }}
      helm-chart-version:
        description: 'Helm chart version'
        value: ${{ jobs.deploy-helm-chart.outputs.helm-chart-version }}

jobs:
  authenticate-and-prepare:
    uses: ./.github/workflows/authenticate-and-prepare.yml
    with:
      app-version: ${{ inputs.app-version }}
      environment: ${{ inputs.environment }}
      debug: ${{ inputs.debug }}
    secrets: inherit


  deploy-helm-chart:
    needs: authenticate-and-prepare
    uses: ./.github/workflows/deploy-helm-chart-workflow.yml