name: Image Creation Workflow

on:
  workflow_call:
    inputs:
      name:
        description: 'Name for greeting'
        required: true
        type: 'string'

jobs:
  build-and-deploy-to-dev:
    environment: development
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      USERNAME: ${{ secrets.OPENAPI_PACKAGE_USER }}
      PASSWORD: ${{ secrets.OPENAPI_PACKAGE_PASSWORD }}

    steps:
      - name: Checkout Github Repository
        uses: actions/checkout@v4

      - name: Login to container repository
        uses: './.github/actions/login-to-aws'
        env:
          ROLE: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.DEV_ECR_REGION }}